### ISSUE TITLE
Update texts to 6. Auflage

### ISSUE THREAD

**Issue by Per-Starke** [gernotstarke/patterns-kompakt.de-site#10]

**Comment by Per-Starke** [comment]
The current text on the home page (amongst other) includes the following:

"
Das Buch [Patterns kompakt 5. Auflage (Springer Vieweg)](https://www.springer.com/de/book/9783662579367) fasst die wichtigsten Entwurfsmuster zusammen, die Sie für Software-Entwicklung benötigen. Software-Entwickler:Innen, -Architekt:Innen und -Designer:Innen finden darin effektiv anwendbare Lösungen für tägliche Entwurfsprobleme. Das Buch gliedert Patterns anhand einiger typischer Aspekte des Software-Entwurfs:

Basismuster für mehr Flexibilität und Wartbarkeit.
Kommunikation & Verteilung
Integration
Persistenz
"

as well as

"
**Die fünfte Auflage:**  
Wir haben Patterns Kompakt überarbeitet, um einige Altersspuren wie ausgestorbene Technologien und Verfahren wegzupolieren. Das Building-Shell-Pattern hat dies nicht überlebt, und die weiterführenden Hinweise in Kapitel 11 mussten runderneuert werden. Auch die Einführung zur Schablonendokumentation wurde aktualisiert.  
Daneben gibt es natürlich auch **Neues**:   
Im Kapitel 9 haben wir das Pattern „Hashwertschlüssel“ ergänzt, das bei der Verarbeitung großer Datenmengen nützlich sein kann. Ebenfalls hinzugekommen ist das Kapitel „Inbetriebnahme“ mit einer Reihe von Tipps, die Ihnen dabei helfen sollen, Software erfolgreich in die Produktion zu überführen. Die Codebeispiele wurden zuletzt auf Java 15 aktualisiert.

Wir wünschen Ihnen viel Freude mit dem Buch und dem Code!	
"

@gernotstarke with respect to the 6. Auflage, how should these texts be changed? And where shall the link point, is the book already available at amazon or somewhere else?

**Comment by gernotstarke** [comment]
Das Buch wird gerade produziert, ist noch NICHT verfügbar. Amazon kennt das schon:
https://www.amazon.de/Patterns-kompakt-Entwurfsmuster-effektive-Softwareentwicklung/dp/3658432330/ref=sr_1_2?__mk_de_DE=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=3TGR7FOWT7S54&keywords=patterns+kompakt&qid=1697730984&sprefix=patterns+kompakt%2Caps%2C102&sr=8-2



der Rückentext:
Titel: Patterns kompakt
Untertitel: Entwurfsmuster für effektive Softwareentwicklung

Text

Patterns kompakt fasst die wichtigsten Entwurfsmuster zusammen, die Sie für Softwareentwicklung benötigen. Softwareentwickler und -architekten finden darin effektiv anwendbare Lösungen für tägliche Entwurfsprobleme. 

Das Buch gliedert Patterns anhand typischer Aspekte des Softwareentwurfs: 
•	Basismuster für mehr Flexibilität und Wartbarkeit
•	Präsentation
•	Kommunikation und Verteilung
•	Integration
•	Persistenz
Die  sechste aktualisierte und erweiterte Auflage enthält ein Kapitel zum Thema Software-Inbetriebnahme.

Patterns kompakt richtet sich an Praktiker: Softwareentwickler, -architekten sowie alle, die einen praxisorientierten Überblick zu Entwurfsmustern benötigen.

Dr. Gernot Starke (INNOQ-Fellow) arbeitet als Berater für Softwarearchitekturen, Entwicklungsprozesse und methodisches Software-Engineering. Nach seinem Informatikstudium promovierte er über Software-Entwicklungsprozesse. Dr. Starke besitzt mehr als 25 Jahre Erfahrung in komplexen IT-Projekten und ist Autor mehrerer erfolgreicher Fachbücher.

Dipl.-Inform. Karl Eilebrecht verfügt über mehr als 15 Jahre praktische Erfahrung in Entwicklung und Consulting moderner E-Business-Systeme. Er war in IT-Projekten unterschiedlicher Branchen als Software-Architekt und -Entwickler tätig und leitet heute agile Entwicklerteams im Big-Data-Umfeld.
