### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by Per-Starke** [gernotstarke/patterns-kompakt.de-site#3]
@gernotstarke on the current page, there is a Javadoc api documentation given [(see here)](http://patterns-kompakt.de/javadoc/index.html), do you also want this on the the site, and if yes, how?

**Comment by gernotstarke** [comment]
take the whole stuff, put it into a new directory, include this in the jekyll _site (via jekyll config)... and hope the links will still work :-)

currently no other idea.

**Comment by Per-Starke** [comment]
Where is the whole stuff for the current website by the way? In the patterns-kompakt repo is only the stuff from the website for auflage 2, not 5, and the api stuff is not in there (sandbox-website-alt-html)..

@gernotstarke
